import { LeftMenu } from "../components/LeftMenu/LeftMenu";
import { MobileMenu } from "../components/MobileMenu/MobileMenu";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <>
      <MobileMenu />
      <main className="flex gap-4 md:gap-2">
        <div className="hidden lg:block md:min-w-[260px] xl:min-w-[205px] 2xl:min-w-[320px]">
          <LeftMenu />
        </div>
        <div className="w-full">{children}</div>
      </main>
    </>
  );
}
